# Generated by Django 2.1 on 2018-08-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='open_to_share',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
