# Generated by Django 2.1 on 2018-09-19 10:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_proposal_open_to_share'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Miss', 'Ms.'), ('Professor', 'Prof.'), ('Doctor', 'Dr.')], max_length=32)),
                ('institute', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered                                 in the format: '9999999999'.                                Up to 10 digits allowed.", regex='^.{10}$')])),
                ('position', models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('industry_people', 'Industry People')], default='student', help_text='Selected catagoery ID shold be required', max_length=32)),
                ('how_did_you_hear_about_us', models.CharField(blank=True, choices=[('FOSSEE website', 'FOSSEE website'), ('Google', 'Google'), ('Social Media', 'Social Media'), ('From other College', 'From other College')], max_length=255)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('activation_key', models.CharField(blank=True, max_length=255, null=True)),
                ('key_expiry_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='about_me',
            new_name='about_the_authors',
        ),
        migrations.AddField(
            model_name='proposal',
            name='name_of_authors',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='proposal',
            name='terms_and_conditions',
            field=models.BooleanField(default='True'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='abstract',
            field=models.TextField(default='abstract', max_length=10),
        ),
    ]
