# Generated by Django 2.1 on 2018-10-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181004_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(help_text='please write it as written in the option         above(CAPS applicable)', max_length=255),
        ),
    ]
