# Generated by Django 2.1 on 2018-10-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181005_0412'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_creation_day',
            field=models.DateField(auto_now=True),
        ),
    ]
