# Generated by Django 2.1 on 2018-10-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_question_question_creation_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_day',
            field=models.DateField(auto_now=True),
        ),
    ]
