# Generated by Django 2.1 on 2018-10-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20181005_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_creation_day',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_day',
            field=models.DateField(),
        ),
    ]
