# Generated by Django 2.1 on 2018-10-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20181005_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerpaper',
            name='attempted',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_day',
            field=models.DateField(help_text='Please follow the format YYYY-MM-DD as it is!'),
        ),
    ]
